name: Retrain Model

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:." >> $GITHUB_ENV
    
    - name: Export DATABASE_URL
      run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

    - name: Run data ingestion pipeline
      run: python -m src.pipeline.data_ingestion_pipeline

    - name: Run training pipeline
      run: python -m src.pipeline.training_pipeline

    
    - name: Commit new model
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add artifacts/best_model.pkl
        git commit -m "Retrained model via GitHub Actions" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main


    - name: Trigger Render deployment
      run: |
        RENDER_URL="${{ secrets.RENDER_DEPLOY_HOOK }}"
        CLEAN_URL=$(echo "$RENDER_URL" | tr -d '[:space:]')
        echo "Deploying to Render at $CLEAN_URL"
        curl -X POST -H "Content-Type: application/json" -d '{}' "$CLEAN_URL"
